name: Build and Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruby-2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
        gemfile:
          - ci/Gemfile.rails-5.2
    name: ${{ matrix.ruby }}-${{ matrix.gemfile }}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
  ruby-3:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        gemfile:
          - ci/Gemfile.rails-6.0
          - ci/Gemfile.rails-6.1
          - ci/Gemfile.rails-7.0
          - ci/Gemfile.rails-7.1
    name: ${{ matrix.ruby }}-${{ matrix.gemfile }}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
